steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom-wordpress:lastest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/custom-wordpress:lastest']

images:
- 'gcr.io/$PROJECT_ID/custom-wordpress:lastest'

